version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh 
    container_name: quikdev-app 
    ports:
      - "3000:3000" 
      - "5555:5555"
    volumes:
      - .:/home/node/app 
    depends_on:
      - db 
    environment:
      - DATABASE_URL=postgresql://postgres:docker@db:5432/quikdev?schema=public
      - JWT_SECRET=stringencryptadagrandeesecreta@123347yhv
      - JWT_EXP=1d
      - NODE_ENV=development
      - PORT=3000

  db:
    build: .docker/postgres 
    container_name: quikdev-db
    restart: always 
    tty: true 
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_PASSWORD=docker 
      - POSTGRES_DB=hubla